# Site settings
title: Andrei E. Tarkhov # site title
description: >- # site description
  I work on understanding the fundamental mechanisms of aging through compbio & applied ai, physics & chaos theory with the goal to find practical ways extend longevity
lang: en-US # default lang
timezone: America/Los_Angeles # set your timezone
image: assets/img/avatar.jpeg # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/TarkhovAndrei/tarkhov.ae # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Andrei E. Tarkhov # author name
  bio: > # tell to the world
    <p>
      longevity researcher with a phd in theoretical physics. my dream is to understand why we age and leverage it to significantly impact human health and longevity.
    </p>
    <p>
      currently at <a href="https://retro.bio">retro.bio</a>, building applied ai to facilitate the development of life-extending and anti-aging therapies.
    </p>
    <p>
      <i><b><a target=_blank href="/subscribe">subscribe</a></b> or reach out to me via email <b><a href="mailto:hi@tarkhov.ae">hi@tarkhov.ae</a></b>, or <b><a href="contact/">other channels</a></b></i>
    </p>

  username: tarkhov # general username
  github: https://github.com/TarkhovAndrei # github username
  twitter: https://x.com/Andrei_Tarkhov # twitter username
  linkedin: https://www.linkedin.com/in/andrei-tarkhov-096ba585/
  facebook: https://www.facebook.com/tarkhov.andrey # facebook username
  researchgate: https://www.researchgate.net/profile/Andrei-Tarkhov
  scholar: https://scholar.google.com/citations?user=2IdDuJoAAAAJ&hl=en
  email: tarkhov.andrey@gmail.com # email adress
  contact_email: hi@tarkhov.ae
  avatar: /assets/img/avatar.jpeg # change with your own avatar

# URL settings
url: "https://tarkhov.ae" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Polyglot configuration
languages: ["en", "ru"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "assets", "js"]
parallel_localization: true

# Collection setting
collections:
  posts:
    output: true
  hobbies:
    output: true
    permalink: /hobbies/:title/

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false
      
# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 10

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess
  - assets
  - assets/videos

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-polyglot
